# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Avoid using print() in production code
    avoid_print: true

    # Prefer single quotes for strings
    prefer_single_quotes: true

    # Always use const where possible
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
