// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv5M8jBn6n9cg8xNIN0aUurwiuDaI8qsg',
    appId: '1:579312720417:web:035d916a2fa0230e392160',
    messagingSenderId: '579312720417',
    projectId: 'spotify101023',
    authDomain: 'spotify101023.firebaseapp.com',
    storageBucket: 'spotify101023.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH_6hkBxhu5GPnTEQGONEoOnTdRgWC7qI',
    appId: '1:579312720417:android:0ef245e5c3f7a206392160',
    messagingSenderId: '579312720417',
    projectId: 'spotify101023',
    storageBucket: 'spotify101023.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ7uqn4a1iaTlDB5QLLwnECmJzW40Y8L4',
    appId: '1:579312720417:ios:09c3ce79ceaca0f6392160',
    messagingSenderId: '579312720417',
    projectId: 'spotify101023',
    storageBucket: 'spotify101023.firebasestorage.app',
    iosBundleId: 'com.example.spotifyCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ7uqn4a1iaTlDB5QLLwnECmJzW40Y8L4',
    appId: '1:579312720417:ios:09c3ce79ceaca0f6392160',
    messagingSenderId: '579312720417',
    projectId: 'spotify101023',
    storageBucket: 'spotify101023.firebasestorage.app',
    iosBundleId: 'com.example.spotifyCloneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv5M8jBn6n9cg8xNIN0aUurwiuDaI8qsg',
    appId: '1:579312720417:web:48f4d9b0f2e0dc13392160',
    messagingSenderId: '579312720417',
    projectId: 'spotify101023',
    authDomain: 'spotify101023.firebaseapp.com',
    storageBucket: 'spotify101023.firebasestorage.app',
  );
}
